{
 "title": "Solariot(Sungrow SG3K-S)",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Generated Today",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "solar_daily_power_yield" }
   ]
  },
  {
   "title": "Generated All time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "solar_total_power_yield", "legendFormat": "Total power yield" }
   ]
  },
  {
   "title": "Generating",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "solar_total_pv_power", "legendFormat": "PV" }
   ]
  },
  {
   "title": "Power(inverter current)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "solar_inverter_current", "legendFormat": "Power(inverter)" }
   ]
  },
  {
   "title": "Generating",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "solar_total_pv_power", "legendFormat": "Power" }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "description": "Voltage",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "solar_grid_voltage", "legendFormat": "Grid" },
    { "expr": "solar_pv1_voltage", "legendFormat": "PV1" }
   ]
  },
  {
   "title": "Voltage(Grid)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "solar_grid_voltage", "legendFormat": "Voltage(Grid)" }
   ]
  },
  {
   "title": "Inverter Temp",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "solar_internal_temp" }
   ]
  },
  {
   "title": "Frequency(Grid)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "solar_grid_frequency", "legendFormat": "Frequency(Grid)" }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "description": "Current",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "solar_inverter_current", "legendFormat": "Grid" },
    { "expr": "solar_pv1_current", "legendFormat": "PV1" }
   ]
  }
 ]
}